name: cs_salvium
repository: https://github.com/somerandomcryptoguy/cs_salvium

packages:
  - packages/**
  - apps/**

command:
  version:
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true

  bootstrap:
    environment:
      sdk: ">=3.5.3 <4.0.0"
      flutter: ">=3.24.0"
    dependencies:
      ffi: ^2.1.0
      logger: ^2.4.0
      meta: ^1.15.0
      plugin_platform_interface: ^2.0.2

    dev_dependencies:
      lints: ^4.0.0
      test: ^1.24.0
      ffigen: ^14.0.0
      flutter_test:
        sdk: flutter
      flutter_lints: ^4.0.0

scripts:
  prepareMoneroC:
    run: dart tools/dart/bin/prepare_monero_c.dart
    description: Clone and prepare the monero_c source. The melos build:* will do this if required.

  build:android:
    run: dart tools/dart/bin/build_libs.dart android
    description: Build the android monero_c libraries

  build:ios:
    run: dart tools/dart/bin/build_libs.dart ios
    description: Build the android monero_c libraries

  build:macos:
    run: dart tools/dart/bin/build_libs.dart macos
    description: Build the android monero_c libraries

  build:linux:
    run: dart tools/dart/bin/build_libs.dart linux
    description: Build the android monero_c libraries

  build:windows:
    run: dart tools/dart/bin/build_libs.dart windows
    description: Build the android monero_c libraries

  copyLibs:
    run: dart tools/dart/bin/copy_libs.dart
    description: Copy monero_c libraries to their respective package locations

  genFFI:
    run: dart tools/dart/bin/gen_ffi.dart
    description: Generate the monero_c dart FFI bindings

  example:
    run: melos exec --scope=apps/example -- flutter run -d linux
    description: Run the example app

  test:
    run: melos exec --dir-exists=test -c 1 -- flutter test
    description: Run tests for all packages

  coverage:
    steps:
      - melos exec --dir-exists=test -c 1 -- flutter test --coverage
      - melos exec --dir-exists=test -c 1 -- genhtml coverage/lcov.info --output-directory=coverage/
    description: Generate coverage for the selected package.