name: example_app
description: "A cs_salvium Flutter example app"
repository: https://github.com/cypherstack/cs_salvium
homepage: https://github.com/cypherstack/cs_salvium
issue_tracker: https://github.com/cypherstack/cs_salvium/issues
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  cs_salvium: ^1.2.1
  cs_salvium_flutter_libs: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
